### ISSUE TITLE
Would you like to share the pre-trained aae?

### ISSUE THREAD

**Issue by kfxw** [browatbn2/3FabRec#1]
Hi!
Thanks for your great work and detailed code sharing.
I noticed that you provided a pre-trained model, and I suppose this model is trained on the full WFLW, right?
Would you like to also share the pre-trained adversarial autoencoder? Since the model seems to be very useful to train on different datasets and tasks but the data preparation and training will take several days.
I would be grateful if you can share this interesting model.
Thx!

**Comment by kfxw** [comment]
I also have a question relating to training aae. As mentioned in the paper, you used 228K images from AffectNet dataset. But there are totally 1M images in this dataset. Do you know why there is such an inconsistency?
Thx!

**Comment by browatbn2** [comment]
Hi, 
the model for WFLW contains the pre-trained autoencoder. It just extends it with additional layers (LMH in the Fabrec class). The encoder wasn't finetuned in this model. 

If you only propagate through the encoder and decoder (Q and P respectively) you essentially get the original autoencoder. 
Alternatively you can also initialize the WFLW model as an instance of the AAE class. This would then just ignore the landmark detection layers. 

I'm not sure if this makes it clear. Let me know if you need more details. :)

**Comment by browatbn2** [comment]
Regarding AffectNet:
Yes, AffectNet contains 1M images in total. However, only about 420K are annotated with facial expression. 
Of these, only ~288K are contain an actual expression (the others are 'None', 'Uncertain', 'Non-face').
I just realized that it should read 288 in the paper instead of 228. I guess that was a typo, sorry about that!  

You can see the stats on the original dataset website in the table at the bottom:
http://mohammadmahoor.com/affectnet/ 

Btw. we didn't use any of the facial expression annotations. We just wanted to get images that actually contain faces and cover a good range of expression.

**Comment by kfxw** [comment]
Yes, I got you.
Thanks very much for your explanation.
I'll come back to you if I need more information.

**Comment by kfxw** [comment]
Hi!
When I use the downloaded pre-trained model, I encounter an error:
`
RuntimeError: storage has wrong size: expected -4910791897195511669 got 32768
`
I browse the Internet and some others said this is due to the conflict when saving the model with multiple processes, as mentioned in https://github.com/NVIDIA/apex/issues/515
So would you please check whether you can load this model properly on your workstation?

**Comment by browatbn2** [comment]
Hm, that's strange, it works on my machine and also used to work on a few others. I'll check... Let me get back to you tomorrow.

**Comment by kfxw** [comment]
Thanks for your reply.
I guess it's my networking issues, since I eventually found the downloaded model was simply broken. I tried to download several times and got the right model. Now it is working.
Thx anyway.
